### ISSUE TITLE
Error when writing CSV file at the end of process

### ISSUE THREAD

**Issue by ssardina** [linanqiu/canvas-submission-time-scraper#4]
Hi,

I am trying to use it on Canvas in RMIT Uni (Australia) and at the end it throws:

```
2018-03-05 11:18:53,938 : INFO : Cross referenced uni S34910
2018-03-05 11:18:54,512 : INFO : Cross referenced uni S36498
2018-03-05 11:18:55,156 : INFO : Writing CSV
Traceback (most recent call last):
  File "canvas-panda-async.py", line 104, in <module>
    submission_time['uni'] = id_uni_name_map[user_id]['uni']
KeyError: 49112

```

do you have any clue what is happening?

thanks!

**Comment by ssardina** [comment]
OK I figured it out. In my uni install, the fields 'uni' and 'name' are not there in the record, only 'user_id' and 'submitted_at'. 

So i changed the code at the end as follows:

```
for submission_time in submission_times:
  user_id = submission_time['user_id']
  try:
    submission_time['uni'] = id_uni_name_map[user_id]['uni']
    submission_time['name'] = id_uni_name_map[user_id]['name']
  except:
      continue

```

**Comment by linanqiu** [comment]
Oh wow someone actually uses this other than me hahaha. So glad this is useful.

Yup `uni` is a Columbia construct.

**Comment by ssardina** [comment]
ahah well, here I am in Australia using your script!

Now, checking it closer seems this code is redundant right?

```
for submission_time in submission_times:
  user_id = submission_time['user_id']
  submission_time['uni'] = id_uni_name_map[user_id]['uni']
  submission_time['name'] = id_uni_name_map[user_id]['name']
```

**Comment by linanqiu** [comment]
Yup this is probably redundant.

**Comment by ssardina** [comment]
OK let me fix it a bit and I will issue you a pull request :-)
